
info:

- name: Jared Morgan
  slack_handle: jaredmorgs
  twitter: http://twitter.com/jaredmorgs
  linkedin: https://www.linkedin.com/in/jaredmorgs
  description: 'Play dual role as tech writer and product manager at Ladbrokes Digital Australia. Pinball fan, podcaster. <a href="http://jaredleonmorgan.net/">jaredleonmorgan.net</a>'
  image: jared_morgan.jpg
  main_cohost: true

- name: Carlee Potter
  slack_handle: carleecomm
  description: 'Head tech writer at Campaign Monitor. Write user manuals out of a love of organisation (& hatred of poor UX). <a href="http://ilikestreetart.com/">ilikestreetart.com</a>'
  image: carlee_potter.jpg
  twitter: https://twitter.com/carleecomm
  linkedin: https://www.linkedin.com/in/carleepotter/
  main_cohost: true

- name: Chris Ward
  slack_handle: chrisward
  description: 'Independent consultant. Born in England, raised in Australia, living in Berlin. Former programmer. <a href="https://www.gregariousmammal.com/">gregariousmammal.com</a>'
  image: chris_ward.jpg
  linkedin: https://www.linkedin.com/in/chrischinchilla/
  twitter: https://twitter.com/chrischinch
  main_cohost: true

- name: Tom Johnson
  slack_handle: tomjohnson
  twitter: http://twitter.com/tomjohnson
  linkedin: https://www.linkedin.com/in/tomjohnson1492
  description: 'Technical writer at Amazon Lab 126. Live in San Francisco Bay area, California. Bike commuter, pickup baller. <a href="http://idratherbewriting.com">idratherbewriting.com</a>'
  image: tom_johnson.jpg
  main_cohost: true

- name: Eva Jackolis
  slack_handle: evalachief
  # twitter: http://twitter.com/evajackolis
  linkedin: https://www.linkedin.com/in/eva-jackolis-a31bb3109/
  description: 'Technical Writer at Seerene in Potsdam. Based in Berlin. Member of WTD Berlin.'
  image: eva_jackolis.png

- name: Pawel Kowaluk
  slack_handle: pawelkowaluk
  twitter: https://twitter.com/pawelkowaluk
  linkedin: https://www.linkedin.com/in/pawelkowaluk/?ppe=1
  description: 'Technical Writer in Poland. DITA geek. Passionate about community. <a href="http://pawelkowaluk.brandyourself.com/">pawalkowaluk.brandyourself.com</a>'
  image: pawel_kowaluk.png

- name: Beth Aitman
  slack_handle: beth.aitman
  twitter: https://twitter.com/baitman
  linkedin: https://www.linkedin.com/in/bethaitman
  description: 'Technical writer at @improbableio. Based in Cambridge, England. Passionate about good UI design. <a href="http://uiwriting.tumblr.com/">uiwriting.tumblr.com/</a>'
  image: beth_aitman.png
